### ISSUE TITLE
cond-> fails with Assert failed: indent was not correctly replaced for form

### ISSUE THREAD

**Issue by hipitihop** [Day8/re-frame-debux#22] opened 2018-04-23 08:44 UTC
@danielcompton I encountered this after updating to Clojure 1.9.0 + ClojureScript 1.10.238 in handler :estimate/toggle-sav-week It's preventing me from continuing with the upgrade as it occurs even with 10x hidden <Ctrl><H> Is there a way to ensure nothing from debux or 10x is involved/running when it is hidden ?

```Uncaught Error: Assert failed: indent was not correctly replaced for form (= sav-id prior-id)

This is a bug, please report it to https://github.com/Day8/re-frame-debux
(integer? indent)
    at debux$common$util$spy_first (util.cljc?rel=1524471491188:343)
    at events.cljs?rel=1524472170279:314
    at events.cljs?rel=1524472170279:314
    at day8$estim8$tarp$events$handler_COLON_toggle_sav_week (events.cljs?rel=1524472170279:314)
    at std_interceptors.cljc?rel=1524471478388:115
    at re_frame$std_interceptors$db_handler__GT_interceptor_$_db_handler_before (std_interceptors.cljc?rel=1524471478388:111)
    at re_frame$interceptor$invoke_interceptor_fn (interceptor.cljc?rel=1524471478163:68)
    at re_frame$interceptor$invoke_interceptors (interceptor.cljc?rel=1524471478163:106)
    at re_frame$interceptor$execute (interceptor.cljc?rel=1524471478163:199)
    at re_frame$events$handle (events.cljc?rel=1524471478213:65)```

**Comment by danielcompton** [comment] 2018-04-23 20:35
If you remove the `fn-traced` from that handler then that will stop it from tracing the function. If you don't set the closure-define then that should also stop hitting this code path. Hiding the 10x panel won't change the code path that traced functions follow, so you can't go that route.

**Comment by mike-thompson-day8** [comment] 2020-05-29 13:21
duplicate of #15?

**Closed as completed** 2020-05-29 13:26 UTC
